version: '3.3' # specify docker-compose version

# Define the services/containers to be run
services:

  webapp:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://db

  redis:
    image: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    command: --smallfiles
#   command: --smallfiles --rest --auth  // if there is a password set in mongo.


volumes:
  mongodata:
#    driver: local-persist
#    driver_opts:
#      mountpoint: ./data